---
repository:
  password: test1234

# List of backup settings, each act as single backp configuration 
backups:
- name: local-test
  type: local
  config:
    sources:
      - /home/haw/Documents/mdn-learning
      - /home/haw/Scripts
    destination: /tmp/wrestic-bkp_local-test
- name: sftp-test
  type: sftp
  config:
    host: sftp host set in ssh config
    sources:
      - /backup/source/path1
      - /backup/source/path2
    destination: /tmp/wrestic-bkp_sftp-test
- name: Descriptive name 3
  type: s3
  config:
    accessKeyId: aws access key id
    secretAccessKey: aws secret access key
    region: aws region
    sources:
      - /backup/source/path1
      - /backup/source/path2
    destination: ${BUCKETNAME}/path/to/backup

# TODO: server block to connect with wrestic-brw
# server:
...
       
